import Head from 'next/head'
// import Slider from '../components/slider'
import PizzaList from '../components/pizzaList'
export default function Home() {
  return (
    <div>
      {/* <Navbar /> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Slider/> */}
      <PizzaList/>
      {/* <Footer /> */}

    {/* <h1 className='text-3xl'>Food Ordering</h1> */}

    
    </div>
  )
}
